version: 2
jobs:
  node-v16-latest:
    docker:
      - image: cimg/node:16.4.1
    steps:
      - checkout
      - run:
          name: Node Info
          command: node --version && npm --version
      - run:
          name: Install yarn
          command: npm install yarn -g
      - run:
          name: Install Dependencies
          command: yarn --immutable
      - run:
          name: Run unit tests.
          command: yarn run ci:coverage
      - run:
          name: Submit coverage data to codecov.
          command: bash <(curl -s https://codecov.io/bash)
          when: on_success
  analysis:
    docker:
      - image: cimg/node:16.4.1
    steps:
      - checkout
      - run:
          name: Install yarn
          command: npm install yarn -g
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Run linting.
          command: yarn run lint
      - run:
          name: Audit Dependencies
          command: yarn run security
workflows:
  version: 2
  validate:
    jobs:
      - analysis:
          filters:
            tags:
              only: /.*/
      - node-v16-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
